// <auto-generated />
using System;
using CasusWebApps.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasusWebApps.Migrations
{
    [DbContext(typeof(WasteDbContext))]
    partial class WasteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasusWebApps.Models.ImageHandler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageHandlers");
                });

            modelBuilder.Entity("CasusWebApps.Models.ImageTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TypeWindow")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ImageHandlerId");

                    b.ToTable("ImageTags");
                });

            modelBuilder.Entity("CasusWebApps.Models.ImageTag", b =>
                {
                    b.HasOne("CasusWebApps.Models.ImageHandler", "ImageHandler")
                        .WithMany("ImageTags")
                        .HasForeignKey("ImageHandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageHandler");
                });

            modelBuilder.Entity("CasusWebApps.Models.ImageHandler", b =>
                {
                    b.Navigation("ImageTags");
                });
#pragma warning restore 612, 618
        }
    }
}
